### ISSUE TITLE
[Bug] particle does not appear while flying, and the environment on the sides does not change

### ISSUE THREAD

**Issue by lostopkk** [lukebemishprojects/Tempest#19] opened 2023-12-22 16:36 UTC
https://github.com/lukebemishprojects/Tempest/assets/50776714/04b93cb9-d0fd-4de3-a9f7-86366882be15

**Comment by lukebemish** [comment] 2023-12-23 00:03
To some degree that's caused by the fact that since the rain is falling at an angle, looking the opposite direction it's falling in (to the side and down) will look like there's no rain, which is noticable in the air but less on the ground; there's not too much I can do about that - it's the same in vanilla looking straight down during a rainstorm. The differing amounts of rain on different sides is caused by a similar phenomenon.

The lack when flying is caused by the fact that the position of rain particles is attached to the ground in some scenarios; I can look into that more, as it's possible to improve to a degree

**Comment by lukebemish** [comment] 2023-12-23 04:55
In theory fixed, to as much of a degree that it can easily be, in 0.1.4; can you check and let me know if it's better?

**Comment by lostopkk** [comment] 2023-12-23 21:47
> In theory fixed, to as much of a degree that it can easily be, in 0.1.4; can you check and let me know if it's better?

the issue was resolved, but the sound remains the same as in the previous version, in which case the noise is only at the bottom and flying does not hear any noise

**Comment by lukebemish** [comment] 2023-12-24 03:27
I believe that's the same as in vanilla; where if you're high in the air, you don't hear rain noise; I'll double check though

**Comment by lukebemish** [comment] 2023-12-26 03:11
Having checked, that behavior does indeed match vanilla, so I am closing this.

**Closed as completed by lukebemish** 2023-12-26 03:11 UTC
